// webclient_react/src/components/contacts/contact-list-item.js
import React from 'react';

const ContactListItem = ({ contact }) => {
  return (
    <div className="item">
      <img className="ui tiny image"
        src={'img/' + contact.img} alt="Person " />
      <div className="content">
        <div className="header">
          {contact.firstname} {contact.lastname}
        </div>
        <div className="description">
          <i className="envelope outline icon"></i>
          {contact.email}</div>
        <div className="meta">
          <div><i className="phone volume icon"></i> {contact.fon}</div>
          <div><i className="mobile alternate icon"></i> {contact.mobil}</div>
        </div>
      </div>
    </div>
  )
}
export default ContactListItem;

// webclient_angular/src/app/contact-list-item/contact-list-item.component.ts
import { Component, Input } from '@angular/core';
import { Contact } from '../shared/contact';

@Component({
  selector: 'app-contact-list-item',
  templateUrl: './contact-list-item.component.html',
  styleUrls: ['./contact-list-item.component.css']
})
export class ContactListItemComponent {
  @Input() contact: Contact;
}

<img class="ui tiny image"
     src="{{contact.img.includes('http') ? contact.img : '../../assets/images/'+contact.img}}"
     appZoom>
<div class="content">
  <div class="header">
    {{contact.firstname}} {{contact.lastname}}
  </div>
  <div class="description">
    <i class="envelope outline icon"></i>
    {{contact.email}}
  </div>
  <div class="meta">
    <div>
      <i class="phone volume icon"></i> 
      {{contact.fon | prefixFon}}
    </div>
    <div>
      <i class="mobile alternate icon"></i> 
      {{contact.mobil | prefixFon}}
    </div>
  </div>
</div>
