// webclient_angular/src/app/contact-details/contact-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ContactStoreService } from '../shared/contact-store.service';
import { Contact } from '../shared/contact';

@Component({
  selector: 'app-contact-details',
  templateUrl: './contact-details.component.html',
  styleUrls: ['./contact-details.component.css']
})
export class ContactDetailsComponent implements OnInit {
  contact: Contact;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private contactService: ContactStoreService
  ) { }

  ngOnInit(): void {
    const params = this.route.snapshot.paramMap;
    this.contactService.getSingle(params.get('id'))
    .subscribe(res => this.contact = res);
  }

  removeContact() {
    if (confirm('Kontakt wirklich löschen?')) {
      this.contactService.remove(this.contact.id + '')
        .subscribe(
          res => this.router.navigate(['../'],
            { relativeTo: this.route }
          )
        );
    }
  }


}

<div *ngIf="contact; else loading" class="ui link cards">
  <div class="card">
    <div class="image">
      <img src="{{contact.img.includes('http') ? contact.img : '../../assets/images/'+contact.img}}">
    </div>
    <div class="content">
      <div class="header">
        <i class="address card outline icon"></i>
        {{contact.firstname}} {{contact.lastname}}
      </div>
      <div class="meta">
        <span class="right floated"><i class="phone volume icon"></i> {{contact.fon}}</span>
        <span><i class="mobile alternate icon"></i> {{contact.mobil}}</span>
      </div>
      <div class="description">
        {{ contact.street }}<br>
        {{ contact.postcode }} {{ contact.place }}
      </div>
    </div>
    <div class="extra content">
      <span class="right floated">
        <i class="birthday cake icon"></i> {{contact.born | date}}
      </span>
      <span>
        <i class="envelope outline icon"></i>
        {{contact.email}}
      </span>
    </div>
  </div>
  <div>
    <button
      class="ui tiny red labeled icon button"
      (click)="removeContact()">
      <i class="remove icon"></i>Kontakt löschen
    </button>
    <button class="ui tiny yellow labeled icon button"
        [routerLink]="['../../contact/edit', contact.id]">
        <i class="write icon"></i>Kontakt bearbeiten
      </button>
  </div>
</div>

<ng-template #loading>
  <div class="ui active centered inline loader"></div>
</ng-template>


<!--div *ngIf="contact" class="ui raised cards">
  <div class="card">
    <div class="image">
      <img src="../../assets/images/{{contact.img || 'people.jpg'}}">
    </div>
    <div class="content">
      <div class="header">{{contact.firstname}} {{contact.lastname}}</div>
      <div class="meta">
        <div><i class="phone volume icon"></i> {{contact.fon}}</div>
        <div><i class="mobile alternate icon"></i> {{contact.mobil}}</div>
      </div>
      <div class="ui grid description" style="overflow-y:auto;white-space:nowrap;">
        <div class="two wide column"><i class="address card outline icon"></i></div>
        <div class="fourteen wide column">{{ contact.street }}<br>
          {{ contact.postcode }} {{ contact.place }}</div>
      </div>
    </div>
    <div class="extra content">
      <div><i class="envelope outline icon"></i>{{contact.email}}</div>
      <div><i class="birthday cake icon"></i> {{contact.born | date}}</div>
    </div>
  </div>
</div-->

// webclient_react_ts/src/components/contacts/contact-details.tsx
import React, { Component } from 'react'
import { RouteComponentProps } from 'react-router'
import axios from 'axios'
import api from '../shared/api'
import { Link } from 'react-router-dom'
import LoadingSpinner from '../shared/loading-spinner'

import Contact from '../../types/Contact'

interface Props extends RouteComponentProps<{id: string}> {}
interface State {
  contact: Contact,
  id: string
}

export default class ContactDetails extends Component<Props, State> {
 
  public componentDidMount() { 
    const { id } = this.props.match.params
    axios.get(`${api.url}/${id}`).then(
      res => this.setState({ id, contact: res.data })
    ).catch(err => console.log(err))
  }

  public deleteContact() {
    if (window.confirm(
      'Soll der Kontakt wirklich gelöscht werden?'
    )) {
      console.log(this.state.id)
      axios({
        url: `${api.url}/${this.state.id}`,
        method: 'delete'
      }).then(
        res => this.props.history.push('/list')
      ).catch(err => console.log(err))
    }    
  }

  public render() {
    const contact: Contact  = this.state && this.state.contact
    return ((!contact) ? (
      <LoadingSpinner />
    ) : (
      <div className="ui segment">
        <div className="ui cards" style={{ marginTop: 10 }}>
          <div className="card">
            <div className="image">
              <img src={ contact.img.includes('http') 
                ? contact.img 
                : 'http://localhost:3001/img/' + contact.img } 
                alt="Person" />
            </div>
            <div className="content">
              <div className="header">
                <i className="address card outline icon" />
                {contact.firstname} {contact.lastname}
              </div>
              <div className="meta">
                <span className="right floated">
                  <i className="phone volume icon" />
                  {contact.fon}
                </span>
                <span>
                  <i className="mobile alternate icon" />
                  {contact.mobil}
                </span>
              </div>
              <div className="description">
                {contact.street}<br />
                {contact.postcode} {contact.place}
              </div>
            </div>
            <div className="extra content">
              <span className="right floated">
                <i className="birthday cake icon" />
                {contact.born}
              </span>
              <span>
                <i className="envelope outline icon" />
                {contact.email}
              </span>
            </div>
          </div>
          <div className="ui center aligned segment">
            <button style={{ marginRight: 20 }}
              className="ui red labeled icon button"
              onClick={ () => this.deleteContact() }>
              <i className="trash icon" /> Kontakt löschen
          </button>
            <Link to={
              {
                pathname: '/edit/' + contact.id,
                state: { fromNotifications: true }
              }
            }>
              <button className="ui violet labeled icon button">
                <i className="write icon" /> Kontakt bearbeiten
              </button>
            </Link>
          </div>
        </div>
      </div>
    )
  )}
}
